version: 0.2

phases:
  install:
    commands:
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - mkdir -p target/beta
    - mkdir target/prod
    - serverless package --package target/beta --stage beta -v -r us-east-1
    - serverless package --package target/prod --stage prod -v -r us-east-1

artifacts:
  files:
  - target/**/*
  - serverless.aws.yml
  - deploy.sh